name: my_flutter_structure
description: With flutter_base_project you can create a multilingual, Authenticated system, handle you're APIs, and routing navigation pages app. I use bloc, flutter_bloc, flutter_secure_storage, dio and flutter_translate.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_secure_storage: ^4.2.1
  dio: ^4.0.0
  data_connection_checker: ^0.3.4
  bloc: ^7.2.1
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  flutter_translate: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
  fonts:
    - family: Lobster-Regular
      fonts:
        - asset: assets/fonts/en/Lobster-Regular.ttf
    - family: Lobster-Regular
      fonts:
        - asset: assets/fonts/en/Roboto-Regular.ttf